LonghornBankWebApp/Models/Stock.cs
using System.ComponentModel.DataAnnotations;

namespace LonghornBankWebApp.Models
{
    public class Stock
    {

        public Int32 StockID { get; set; }

        [Display(Name = "Stock Name")]
        [Required(ErrorMessage = "Stock Name is required")]
        public String StockName { get; set; }

        [Display(Name = "Stock Price")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        [Required(ErrorMessage = "Stock Price is required")]
        public Decimal CurrentPrice { get; set; }

        [Display(Name = "Stock Symbol")]
        [RegularExpression(@"^[a-zA-Z]{1,5}$", ErrorMessage = "Stock symbol must be 1-5 letters")]
        [Required(ErrorMessage = "Ticker symbol is required")]
        public String TickerSymbol { get; set; }


        // navigational properties

        public StockType StockType { get; set; }

        public List<StockTransaction> StockTransactions { get; set; }

        public List<StockPrice> StockPrices { get; set; }

        public Stock()
        {
            if (StockTransactions == null)
            {
                StockTransactions = new List<StockTransaction>();

            }
            if (StockPrices == null)
            {
                StockPrices = new List<StockPrice>();
            }
        }
    }
}

LonghornBankWebApp/Models/StockType.cs
using System.ComponentModel.DataAnnotations;

namespace LonghornBankWebApp.Models
{

    public class StockType
    {

        public Int32 StockTypeID { get; set; }

        [Display(Name = "Stock Type")]
        public String StockTypeName { get; set; }



        // Navigational propereties

        public List<Stock> Stocks { get; set; }


        public StockType()
        {
            if (Stocks == null)
            {
                Stocks = new List<Stock>();
            }

        }


    }
}

LonghornBankWebApp/Controllers/StockTypesController.cs
using LonghornBankWebApp.DAL;
using LonghornBankWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LonghornBankWebApp.Controllers
{
    [Authorize]
    public class StockTypesController : Controller
    {
        private readonly AppDbContext _context;

        public StockTypesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: StockTypes
        public async Task<IActionResult> Index()
        {
            return View(await _context.StockTypes.ToListAsync());
        }

        // GET: StockTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.StockTypes == null)
            {
                return NotFound();
            }

            var stockType = await _context.StockTypes.Include(s => s.Stocks)
                .FirstOrDefaultAsync(m => m.StockTypeID == id);


            if (stockType == null)
            {
                return NotFound();
            }

            return View(stockType);
        }

        // GET: StockTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: StockTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StockTypeID,StockTypeName")] StockType stockType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(stockType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(stockType);
        }

        // GET: StockTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.StockTypes == null)
            {
                return NotFound();
            }

            var stockType = await _context.StockTypes.FindAsync(id);
            if (stockType == null)
            {
                return NotFound();
            }
            return View(stockType);
        }

        // POST: StockTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StockTypeID,StockTypeName")] StockType stockType)
        {
            if (id != stockType.StockTypeID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(stockType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StockTypeExists(stockType.StockTypeID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(stockType);
        }

        // GET: StockTypes/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.StockTypes == null)
            {
                return NotFound();
            }

            var stockType = await _context.StockTypes
                .FirstOrDefaultAsync(m => m.StockTypeID == id);
            if (stockType == null)
            {
                return NotFound();
            }

            return View(stockType);
        }

        // POST: StockTypes/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    if (_context.StockTypes == null)
        //    {
        //        return Problem("Entity set 'AppDbContext.StockTypes'  is null.");
        //    }
        //    var stockType = await _context.StockTypes.FindAsync(id);
        //    if (stockType != null)
        //    {
        //        _context.StockTypes.Remove(stockType);
        //    }

        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        private bool StockTypeExists(int id)
        {
            return _context.StockTypes.Any(e => e.StockTypeID == id);
        }
    }
}

LonghornBankWebApp/Controllers/StocksController.cs
using Highsoft.Web.Mvc.Charts;
using LonghornBankWebApp.DAL;
using LonghornBankWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace LonghornBankWebApp.Controllers
{
    public class StocksController : Controller
    {
        private readonly AppDbContext _context;

        public StocksController(AppDbContext context)
        {
            _context = context;
        }





        // GET: Stocks
        public async Task<IActionResult> Index()
        {
            return View(await _context.Stocks.Include(s => s.StockType).AsNoTracking().ToListAsync());

        }

        private IEnumerable<SelectListItem> GetStockTypes()

        {
            List<StockType> StockTypes = _context.StockTypes.ToList();

            List<SelectListItem> StockTypeList = new();

            foreach (StockType s in StockTypes)
            {
                SelectListItem newStockType = new()
                {
                    Text = s.StockTypeName,
                    Value = s.StockTypeID.ToString()
                };
                StockTypeList.Add(newStockType);
            }

            return StockTypeList;
        }


        // GET: Stocks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Stocks == null)
            {
                return NotFound();
            }


            var stock = await _context.Stocks.Where(s => s.StockID == id).Select(
                s => new
                {
                    Stock = s,
                    Prices = s.StockPrices.Select(sp => new LineSeriesData { Y = Decimal.ToDouble(sp.CurrentPrice) }),
                    Dates = s.StockPrices.Select(sp => sp.Date.ToString())
                }).AsNoTracking().FirstOrDefaultAsync();

            if (stock == null)
            {
                return NotFound();
            }

            //ADDED: Create a line graph of the historical stock price
            ViewData["PriceX"] = stock.Dates.ToList();
            ViewData["PriceY"] = stock.Prices.ToList();



            return View(stock.Stock);
        }




        // GET: Stocks/Create
        public IActionResult Create()
        {
            ViewBag.Types = GetStockTypes();
            return View();
        }

        // POST: Stocks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Stock stock, int? SelectedID, bool? modify)
        {

            if (SelectedID == null)
            {
                ModelState.AddModelError("", "Valid stock type is required");
                ViewBag.Types = GetStockTypes();
                return View(stock);
            }

            // ensure that no ticker symbol is identical
            Stock dbStock = _context.Stocks.FirstOrDefault(s => s.TickerSymbol == stock.TickerSymbol);

            if (dbStock != null)
            {
                ModelState.AddModelError("TickerSymbol", "Ticker symbol must be unique");
                ViewBag.Types = GetStockTypes();
                return View(stock);
            }
            if (decimal.Compare(stock.CurrentPrice, (decimal)0.01) < 0)
            {
                ModelState.AddModelError("CurrentPrice", "Current price must be greater than $0.01");
                ViewBag.Types = GetStockTypes();
                return View(stock);

            }

            StockType dbStockType = _context.StockTypes.FirstOrDefault(s => s.StockTypeID == SelectedID);
            stock.StockType = dbStockType;

            if (ModelState.IsValid)
            {

                if (modify == false)
                {
                    ModelState.AddModelError("Valid", "Confirm to create " + stock.StockName + " stock with current price $"
                        + stock.CurrentPrice + " and type " + stock.StockType.StockTypeName);
                    ViewBag.Types = GetStockTypes();
                    return View(stock);
                }
                else if (modify == true)
                {
                    _context.Add(stock);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }


            }
            return View(stock);
        }

        // GET: Stocks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Stocks == null)
            {
                return NotFound();
            }

            var stock = await _context.Stocks.FindAsync(id);
            if (stock == null)
            {
                return NotFound();
            }
            return View(stock);
        }

        // POST: Stocks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StockID,StockName,CurrentPrice,TickerSymbol")] Stock stock)
        {
            if (id != stock.StockID)
            {
                return NotFound();
            }

            if (stock.CurrentPrice < (decimal)0.01)
            {
                ModelState.AddModelError("CurrentPrice", "Current price must be greater than $0.01");
                return View(stock);
            }

            try
            {
                Stock dbStock = _context.Stocks.FirstOrDefault(s => s.StockID == id);
                dbStock.CurrentPrice = stock.CurrentPrice;
                _context.Update(dbStock);

                //ADDED: add stock price history
                StockPrice sp = new()
                {
                    Stock = dbStock,
                    CurrentPrice = stock.CurrentPrice,
                    Date = DateTime.Now
                };
                _context.Add(sp);

                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!StockExists(stock.StockID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));

        }

        // GET: Stocks/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Stocks == null)
            {
                return NotFound();
            }

            var stock = await _context.Stocks
                .FirstOrDefaultAsync(m => m.StockID == id);
            if (stock == null)
            {
                return NotFound();
            }

            return View(stock);
        }

        // POST: Stocks/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    if (_context.Stocks == null)
        //    {
        //        return Problem("Entity set 'AppDbContext.Stocks'  is null.");
        //    }
        //    var stock = await _context.Stocks.FindAsync(id);
        //    if (stock != null)
        //    {
        //        _context.Stocks.Remove(stock);
        //    }

        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        private bool StockExists(int id)
        {
            return _context.Stocks.Any(e => e.StockID == id);
        }
    }
}

LonghornBankWebApp/Views/Stocks/Create.cshtml
@model LonghornBankWebApp.Models.Stock

@{
    ViewData["Title"] = "Create";
}

<h1>Add Stock</h1>
<hr />

@section containerbottom{

    <div class="container min-vh-100 mt-4">
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="StockName" class="control-label"></label>
                        <input asp-for="StockName" class="form-control" />
                        <span asp-validation-for="StockName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CurrentPrice" class="control-label"></label>
                        <input asp-for="CurrentPrice" class="form-control" />
                        <span asp-validation-for="CurrentPrice" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="TickerSymbol" class="control-label"></label>
                        <input asp-for="TickerSymbol" class="form-control" />
                        <span asp-validation-for="TickerSymbol" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label>Stock Type</label>
                        @Html.DropDownList("SelectedID", @ViewBag.Types, "Select a Stock", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @if (ViewData.ModelState.Keys.Contains("Valid"))
                        {
                            <input type="submit" value="Confirm" asp-route-modify="@true" class="btn btn-success" />
                            <a asp-action="Create" class="btn btn-danger">Cancel</a>
                        }
                        else
                        {
                            <input type="submit" value="Create" asp-route-modify="@false" class="btn btn-primary" />

                        }
                    </div>
                </form>
            </div>
            <div class="col-md-4">

                @if (ViewData.ModelState.Keys.Contains("Valid"))
                {
                    <div class="alert alert-success" role="alert">
                        <p> @ViewData.ModelState["Valid"].Errors[0].ErrorMessage</p>
                    </div>

                }
            </div>
        </div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>

    </div>
}

LonghornBankWebApp/Views/Stocks/Delete.cshtml
@model LonghornBankWebApp.Models.Stock

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Stock</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StockName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StockName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CurrentPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CurrentPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TickerSymbol)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TickerSymbol)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="StockID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LonghornBankWebApp/Views/Stocks/Details.cshtml
<script src="~/lib/highcharts/highcharts.js"></script>
<script src="~/lib/highcharts/exporting.js"></script>
<script src="~/lib/highcharts/accessibility.js"></script>

@model LonghornBankWebApp.Models.Stock
@using Highsoft.Web.Mvc.Charts
@using Highsoft.Web.Mvc.Charts.Rendering;

@{
    ViewData["Title"] = "Details";

    var lineChart = new Highcharts
    {
        Title = new Title { Text = "Historical Price"},

        XAxis = new List<XAxis>
        {
            new XAxis
            {
                Categories = ViewData["PriceX"] as List<string>
            }
        },

        YAxis = new List<YAxis>
        {
            new YAxis
            {
                Title = new YAxisTitle
                {
                    Text = "Price ($)"
                    
                },
                PlotLines = new List<YAxisPlotLines>
                {
                    new YAxisPlotLines
                    {
                        Value = 0,
                        Width = 1,
                        Color = "#00a9b7"
                        
                    }
                }
            }
        },
        Series = new List<Series>
        {
            new LineSeries
            {
                Name = "Price",
                Data = ViewData["PriceY"] as List<LineSeriesData>,
                Color = "#a6cd57"

            }
        }


    };
    lineChart.ID = "chart";
    var renderer = new HighchartsRenderer(lineChart);



}

@section container
{
<div class="container min-vh-100">
        
    <h1 class="text-center">Stock Details</h1>

    <div>
        <hr />
        <div class="row">
            <dl class="col">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.StockName)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.StockName)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.CurrentPrice)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.CurrentPrice)
            </dd>
            <dt class = "col-sm-4">
                @Html.DisplayNameFor(model => model.TickerSymbol)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.TickerSymbol)
            </dd>
        
            </dl>

            <dl class="col">
                @Html.Raw(renderer.RenderHtml())
            </dl>

        
        </div>
    
    </div>
    <div>
        @if(User.IsInRole("Admin")){
            <a asp-action="Edit" asp-route-id="@Model?.StockID">Edit</a>

        }
        <a asp-action="Index">Back to List</a>
    </div>

        
</div>



}

LonghornBankWebApp/Views/Stocks/Edit.cshtml
@model LonghornBankWebApp.Models.Stock

@{
    ViewData["Title"] = "Edit";
}

<h1>Update Current Price</h1>
<hr />

@section containerbottom{

    <div class="container min-vh-100 mt-4">
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="StockID" />
                    @*<div class="form-group">
                <label asp-for="StockName" class="control-label"></label>
                <input asp-for="StockName" class="form-control" />
                <span asp-validation-for="StockName" class="text-danger"></span>
                </div>*@
                    <div class="form-group">
                        <label asp-for="CurrentPrice" class="control-label"></label>
                        <input asp-for="CurrentPrice" class="form-control" />
                        <span asp-validation-for="CurrentPrice" class="text-danger"></span>
                    </div>
                    @*<div class="form-group">
                <label asp-for="TickerSymbol" class="control-label"></label>
                <input asp-for="TickerSymbol" class="form-control" />
                <span asp-validation-for="TickerSymbol" class="text-danger"></span>
                </div>*@
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </div>
}

LonghornBankWebApp/Views/Stocks/Index.cshtml
@model IEnumerable<LonghornBankWebApp.Models.Stock>

@{
    ViewData["Title"] = "Stocks";
}

<h1 class="text-center">Current Stock Offerings</h1>

@if (User.IsInRole("Admin"))
{
    <p>
        <a asp-action="Create" class="btn btn-primary">Add New Stock</a>
        <a asp-action="Create" asp-controller="StockTypes" class="btn btn-primary">Add New Stock Type</a>

    </p>
}

<table class="table table-striped table-hover table-bordered" style="border-color:#ffd600">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TickerSymbol)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StockType.StockTypeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StockName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CurrentPrice)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TickerSymbol)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StockType.StockTypeName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StockName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CurrentPrice)
                </td>
                <td>

                    <a asp-action="Details" asp-route-id="@item.StockID">Details</a>

                    @if (User.IsInRole("Admin"))
                    {
                        <a asp-action="Edit" asp-route-id="@item.StockID">Edit</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>