LonghornBankWebApp/Controllers/MessagesController.cs
using LonghornBankWebApp.DAL;
using LonghornBankWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;



namespace LonghornBankWebApp.Controllers
{

    [Authorize(Roles = "Admin, Customer")]
    public class MessagesController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public MessagesController(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Messages
        public async Task<IActionResult> Index()
        {

            AppUser user = _userManager.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);

            List<Message> Pending = await _context.Messages.Where(m => m.Admins.Contains(user)).ToListAsync();

            List<Message> Viewed = await _context.Messages.Where(m => m.Admins.Contains(user) == false).ToListAsync();


            return View(Pending.OrderByDescending(x => x.MessageID));
        }

        // GET: Messages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Messages == null)
            {
                return NotFound();
            }

            var message = await _context.Messages
                .FirstOrDefaultAsync(m => m.MessageID == id);
            if (message == null)
            {
                return NotFound();
            }

            return View(message);
        }

        private SelectList GetAllAdmins()
        {
            List<AppUser> AllAdmins = _userManager.GetUsersInRoleAsync("Admin").Result.ToList();
            // select admins that are isActive
            var query = from a in AllAdmins where a.IsActive == true select a;

            List<AppUser> ActiveAdmins = query.ToList<AppUser>();

            //AppUser All = new AppUser() { Email = "All", FirstName = "All", LastName = "Admins" };
            //ActiveAdmins.Add(All);

            SelectList AllAdminsList = new(ActiveAdmins.OrderBy(u => u.FirstName), "Email", "FullName");

            return AllAdminsList;
        }

        // GET: Messages/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewBag.Admins = GetAllAdmins();
            return View();
        }

        // POST: Messages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MessageID,Subject,Info")] Message message, string Admin)
        {
            if (ModelState.IsValid)
            {
                // all admins
                if (Admin == null)
                {
                    List<AppUser> AllAdmins = _userManager.GetUsersInRoleAsync("Admin").Result.ToList();

                    var query = from a in AllAdmins where a.IsActive == true select a;

                    List<AppUser> ActiveAdmins = query.ToList<AppUser>();

                    message.Admins = ActiveAdmins;

                    message.Receiver = "All";
                }
                else
                {
                    AppUser user = await _userManager.FindByEmailAsync(Admin);

                    if (user.Email == User.Identity.Name)
                    {
                        ModelState.AddModelError("Receiver", "You cannot send a message to yourself");
                        ViewBag.Admins = GetAllAdmins();
                        return View(message);
                    }
                    message.Admins = new List<AppUser>
                    {
                        user
                    };

                    message.Receiver = user.FullName;
                }
                message.Date = DateTime.Now;
                message.Sender = User.Identity.Name;

                _context.Add(message);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Admins = GetAllAdmins();
            return View(message);
        }
        // function that returns the number of messages for a user
        public int GetNumberOfMessages()
        {
            AppUser user = _userManager.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);

            List<Message> Pending = _context.Messages.Where(m => m.Admins.Contains(user)).ToList();

            return Pending.Count;
        }

        public async Task<IActionResult> Read(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            Message message = await _context.Messages.Include(m => m.Admins).FirstOrDefaultAsync(m => m.MessageID == id);

            AppUser user = _userManager.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);

            message.Admins.Remove(user);

            _context.Update(message);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        // GET: Messages/Delete/5
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Messages == null)
            {
                return NotFound();
            }

            var message = await _context.Messages
                .FirstOrDefaultAsync(m => m.MessageID == id);
            if (message == null)
            {
                return NotFound();
            }

            return View(message);
        }

        // POST: Messages/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    if (_context.Messages == null)
        //    {
        //        return Problem("Entity set 'AppDbContext.Messages'  is null.");
        //    }
        //    var message = await _context.Messages.FindAsync(id);
        //    if (message != null)
        //    {
        //        _context.Messages.Remove(message);
        //    }

        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        private bool MessageExists(int id)
        {
            return _context.Messages.Any(e => e.MessageID == id);
        }
    }
}

LonghornBankWebApp/Controllers/StocksController.cs
using Highsoft.Web.Mvc.Charts;
using LonghornBankWebApp.DAL;
using LonghornBankWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace LonghornBankWebApp.Controllers
{
    public class StocksController : Controller
    {
        private readonly AppDbContext _context;

        public StocksController(AppDbContext context)
        {
            _context = context;
        }





        // GET: Stocks
        public async Task<IActionResult> Index()
        {
            return View(await _context.Stocks.Include(s => s.StockType).AsNoTracking().ToListAsync());

        }

        private IEnumerable<SelectListItem> GetStockTypes()

        {
            List<StockType> StockTypes = _context.StockTypes.ToList();

            List<SelectListItem> StockTypeList = new();

            foreach (StockType s in StockTypes)
            {
                SelectListItem newStockType = new()
                {
                    Text = s.StockTypeName,
                    Value = s.StockTypeID.ToString()
                };
                StockTypeList.Add(newStockType);
            }

            return StockTypeList;
        }


        // GET: Stocks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Stocks == null)
            {
                return NotFound();
            }


            var stock = await _context.Stocks.Where(s => s.StockID == id).Select(
                s => new
                {
                    Stock = s,
                    Prices = s.StockPrices.Select(sp => new LineSeriesData { Y = Decimal.ToDouble(sp.CurrentPrice) }),
                    Dates = s.StockPrices.Select(sp => sp.Date.ToString())
                }).AsNoTracking().FirstOrDefaultAsync();

            if (stock == null)
            {
                return NotFound();
            }

            //ADDED: Create a line graph of the historical stock price
            ViewData["PriceX"] = stock.Dates.ToList();
            ViewData["PriceY"] = stock.Prices.ToList();



            return View(stock.Stock);
        }




        // GET: Stocks/Create
        public IActionResult Create()
        {
            ViewBag.Types = GetStockTypes();
            return View();
        }

        // POST: Stocks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Stock stock, int? SelectedID, bool? modify)
        {

            if (SelectedID == null)
            {
                ModelState.AddModelError("", "Valid stock type is required");
                ViewBag.Types = GetStockTypes();
                return View(stock);
            }

            // ensure that no ticker symbol is identical
            Stock dbStock = _context.Stocks.FirstOrDefault(s => s.TickerSymbol == stock.TickerSymbol);

            if (dbStock != null)
            {
                ModelState.AddModelError("TickerSymbol", "Ticker symbol must be unique");
                ViewBag.Types = GetStockTypes();
                return View(stock);
            }
            if (decimal.Compare(stock.CurrentPrice, (decimal)0.01) < 0)
            {
                ModelState.AddModelError("CurrentPrice", "Current price must be greater than $0.01");
                ViewBag.Types = GetStockTypes();
                return View(stock);

            }

            StockType dbStockType = _context.StockTypes.FirstOrDefault(s => s.StockTypeID == SelectedID);
            stock.StockType = dbStockType;

            if (ModelState.IsValid)
            {

                if (modify == false)
                {
                    ModelState.AddModelError("Valid", "Confirm to create " + stock.StockName + " stock with current price $"
                        + stock.CurrentPrice + " and type " + stock.StockType.StockTypeName);
                    ViewBag.Types = GetStockTypes();
                    return View(stock);
                }
                else if (modify == true)
                {
                    _context.Add(stock);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }


            }
            return View(stock);
        }

        // GET: Stocks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Stocks == null)
            {
                return NotFound();
            }

            var stock = await _context.Stocks.FindAsync(id);
            if (stock == null)
            {
                return NotFound();
            }
            return View(stock);
        }

        // POST: Stocks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StockID,StockName,CurrentPrice,TickerSymbol")] Stock stock)
        {
            if (id != stock.StockID)
            {
                return NotFound();
            }

            if (stock.CurrentPrice < (decimal)0.01)
            {
                ModelState.AddModelError("CurrentPrice", "Current price must be greater than $0.01");
                return View(stock);
            }

            try
            {
                Stock dbStock = _context.Stocks.FirstOrDefault(s => s.StockID == id);
                dbStock.CurrentPrice = stock.CurrentPrice;
                _context.Update(dbStock);

                //ADDED: add stock price history
                StockPrice sp = new()
                {
                    Stock = dbStock,
                    CurrentPrice = stock.CurrentPrice,
                    Date = DateTime.Now
                };
                _context.Add(sp);

                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!StockExists(stock.StockID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));

        }

        // GET: Stocks/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Stocks == null)
            {
                return NotFound();
            }

            var stock = await _context.Stocks
                .FirstOrDefaultAsync(m => m.StockID == id);
            if (stock == null)
            {
                return NotFound();
            }

            return View(stock);
        }

        // POST: Stocks/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    if (_context.Stocks == null)
        //    {
        //        return Problem("Entity set 'AppDbContext.Stocks'  is null.");
        //    }
        //    var stock = await _context.Stocks.FindAsync(id);
        //    if (stock != null)
        //    {
        //        _context.Stocks.Remove(stock);
        //    }

        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        private bool StockExists(int id)
        {
            return _context.Stocks.Any(e => e.StockID == id);
        }
    }
}

LonghornBankWebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@using Microsoft.AspNetCore.Identity
@inject UserManager<AppUser> userManager;
@inject IHttpContextAccessor _context;

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet"/>
    <!-- Custom Format-->
    <link href="~/css/site.css" rel="stylesheet" />

    
    
</head>
<body>
    <!--This is the code for the navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(191, 87, 0)">
        <div class="container-fluid">

            <!--This is the code for the "hamburger menu" button -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav-content" aria-controls="nav-content" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <!--This is the link to the home page - you can leave this as is -->
            <a asp-controller="Home" asp-action="Index" class="navbar-brand "><i class="fa fa-home"></i></a>

            @{
                var user = await userManager.GetUserAsync(_context.HttpContext.User);
                
            }
            <!--everything in this section will collapse when the screen is small -->
            <div class="collapse navbar-collapse" id="nav-content">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    @if (User.IsInRole("Customer") && @user.UserHasAccount)
                    {
                        <li class="nav-item">
                            <a asp-controller="BankAccounts" asp-action="Index" class="nav-link">Accounts</a>
                        </li>

                        <li class="nav-item">
                            <a asp-controller="Transactions" asp-action="Index" class="nav-link">Transactions</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Stock Portfolio</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-controller="StockPortfolio" asp-action="Index" >Home</a></li>
                                <li><a class="dropdown-item"  asp-controller="Stocks" asp-action="Index">Stock Offerings</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-controller="StockTransactions" asp-action="Create">Buy Stock</a></li>
                                <li><a class="dropdown-item" asp-controller="StockTransactions" asp-action="SellStock" asp-route-name ="@user.Email">Sell Stock</a></li>

                            </ul>
                        </li>


                    }
                    @if (User.IsInRole("Customer") && @user.UserHasAccount == false)
                    {
                        <li class="nav-item">
                            <a asp-controller="BankAccounts" asp-action="Create" class="nav-link">Open Checkings, Savings, or IRA Account</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="StockPortfolio" asp-action="Index" class="nav-link">Open Stock Portfolio</a>
                         </li>
                    }

                    @if (User.IsInRole("Customer")){
                        <li class="nav-item">
                            <span class="badge badge-pill" style="float:right;margin-bottom:-12px; background-color:red"></span>
                            <a asp-action="Index" asp-controller="Messages" class="nav-link">Alerts</a>
                        </li>
                        
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <a asp-controller="BankAccounts" asp-action="Index" class="nav-link">Accounts</a>
                        </li>
@*
                        <li class="nav-item">
                            <a asp-controller="Transactions" asp-action="Index" class="nav-link">Transactions</a>
                        </li>*@
                        
                       
                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Manage
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropDown1">
                                <li>
                                    <a asp-controller="RoleAdmin" asp-action="Index" class="dropdown-item">Manage Users</a>
                                </li>
                                <li>
                                    <a asp-controller="RoleAdmin" asp-action="ManageTask" class="dropdown-item">Manage Tasks</a>
                                </li>
                            </ul>
                        </li>



                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Stocks
                          </a>
                          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a asp-controller="StockTypes" asp-action="Index" class="dropdown-item">Stock Types</a>
                            </li>
                            <li>
                                <a asp-controller="Stocks" asp-action="Index" class="dropdown-item">Stock Offerings</a>
                            </li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" asp-action="Create" asp-controller="Stocks">Add Stock</a></li>
                            <li><a class="dropdown-item" asp-action="Create" asp-controller="StockTypes">Add Stock Type</a></li>
                            
                          </ul>
                        </li>

                        <li class="nav-item">
                            <span class="badge badge-pill" style="float:right;margin-bottom:-12px; background-color:red"></span>
                            <a asp-action="Index" asp-controller="Messages" class="nav-link">Inbox</a>
                        </li>
                     
                    }

                    @if (User.IsInRole("Employee") && @user.IsActive)
                    {
                        <li class="nav-item">
                            <a asp-controller="RoleAdmin" asp-action="Index" class="nav-link">Manage Users</a>
                        </li>
                        @*<li class="nav-item">
                            <a asp-controller="Transactions" asp-action="Index" class="nav-link">Transactions</a>
                        </li>*@
                        <li class="nav-item">
                            <a asp-controller="BankAccounts" asp-action="Index" class="nav-link">Accounts</a>
                        </li>
                        <li class="nav-item ">
                            <a asp-controller="Stocks" asp-action="Index" class="nav-link">Stock Offerings</a>
                        </li>
                    }
                    @if (User.Identity.IsAuthenticated == false)
                    {
                        <li class="nav-item ">
                            <a asp-controller="Stocks" asp-action="Index" class="nav-link">Stock Offerings</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Home" asp-action="HowTo" class="nav-link">How to Use</a>

                        </li>
                    }

                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>

        </div>
    </nav>

    <!-- Used for pages that need full page length-->
    @RenderSection("container", required: false)

    <!-- Used for pages that need full page width-->
    @RenderSection("containerFluid", required: false)

    
    <!--this is the main content section of the website (does not use full page width) -->
    <div class="container">
        <!--NOTE: This is where the code from the main view is inserted -->
        @RenderBody()
    </div>
    <!-- Used for pages that need full page length below the body-->
    @RenderSection("containerbottom", required: false)

    <!--This code references different script libraries to make your page responsive -->
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.bundle.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    @RenderSection("Scripts", required: false)
    
    @if(User.Identity.IsAuthenticated){
        <script type="text/javascript">
                $(document).ready(function () {
                    $.ajax({
                        url: '@Url.Action("GetNumberOfMessages", "Messages")',
                        type: 'GET',
                        success: function (data) {
                            if (data > 0) {
                                $(".badge").text(data);
                            }
                        
                        }
                    });

                });

        </script>
    }
    
    <footer class="text-lg-start">
        <div class="text-center text-white p-3 bg-secondary">
            © 2022 Longhorn Bank & Trust Corp
        </div>
    </footer>
</body>
</html>