LonghornBankWebApp/Controllers/StockTransactionsController.cs
using LonghornBankWebApp.DAL;
using LonghornBankWebApp.Models;
using LonghornBankWebApp.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace LonghornBankWebApp.Controllers
{
    [Authorize]

    public class StockTransactionsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;


        public StockTransactionsController(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;


        }

        // GET: StockTransactions
        public async Task<IActionResult> Index()
        {
            return View(await _context.StockTransactions.ToListAsync());
        }

        // GET: StockTransactions/Details/5
        public async Task<IActionResult> Details(int? id, int? stockLeft)
        {
            if (id == null || _context.StockTransactions == null)
            {
                return NotFound();
            }

            StockTransaction stockTransaction = await _context.StockTransactions.Include(s => s.StockPortfolio).Include(s => s.Stock).ThenInclude(s => s.StockType)
                .FirstOrDefaultAsync(r => r.StockTransactionNumber == id);

            if (stockTransaction == null)
            {
                return NotFound();
            }

            ViewBag.Left = stockLeft;

            return View(stockTransaction);
        }

        public async Task<IActionResult> StockTransDetails(int? id)
        {
            if (id == null || _context.StockTransactions == null)
            {
                return NotFound();
            }

            StockTransaction stockTransaction = await _context.StockTransactions.Include(s => s.StockPortfolio).Include(s => s.Stock).ThenInclude(s => s.StockType)
                .FirstOrDefaultAsync(r => r.StockTransactionID == id);

            if (stockTransaction == null)
            {
                return NotFound();
            }

            return View(stockTransaction);
        }

        // GET: StockTransactions/Create
        public IActionResult Create()
        {
            ViewBag.DropDown = GetStockDropDown();
            return View();
        }




        // POST: StockTransactions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(StockTransaction stockTransaction, int? SelectedStock, bool? modify)
        {
            AppUser u = _userManager.FindByNameAsync(User.Identity.Name).Result;
            StockPortfolio sp = _context.StockPortfolios.FirstOrDefault(s => s.User.UserName == User.Identity.Name);

            if (sp == null)
            {
                return NotFound();
            }

            if (u.IsActive == false || sp.isActive == false)
            {
                return RedirectToAction("Index", "StockPortfolio", new { message = "Your account is not active. Please contact an administrator to activate your account." });

            }
            if (ModelState.IsValid && SelectedStock != null)
            {

                int result = DateTime.Compare(DateTime.Now.Date, stockTransaction.TransactionDate.Date);
                //ensure stock transaction date is today or later
                if (result > 0)
                {
                    ModelState.AddModelError("TransactionDate", "Transaction date must be today or later");
                    ViewBag.DropDown = GetStockDropDown();
                    return View(stockTransaction);
                }

                // Find stock from database

                Stock st = _context.Stocks.Include(s => s.StockType).FirstOrDefault(s => s.StockID == SelectedStock);

                if (st != null)
                {
                    // take into account the $10 fee
                    Decimal total = (stockTransaction.NumberOfShares * st.CurrentPrice) + 10;
                    StockPortfolio stp = _context.StockPortfolios.FirstOrDefault(s => s.User.UserName == User.Identity.Name);

                    // Ensure enough funds are available
                    if (total > stp.CashValuePortion)
                    {
                        // add model error and return to create view
                        ModelState.AddModelError("Not Enough Money!", "You do not have enough money in your portfolio to buy this many shares");
                        ViewBag.DropDown = GetStockDropDown();
                        return View(stockTransaction);

                    }
                    else if (modify == false)
                    {
                        //ModelState.SetModelValue("NumberOfShares", new ValueProviderResult(stockTransaction.NumberOfShares.ToString(), System.Globalization.CultureInfo.CurrentCulture));
                        //ModelState.SetModelValue("TransactionDate", new ValueProviderResult(stockTransaction.TransactionDate.ToString(), System.Globalization.CultureInfo.CurrentCulture));
                        ModelState.AddModelError("Succesful", "Confirm to buy " + stockTransaction.NumberOfShares + " shares of " + st.StockName + " for $" + total + " on " + stockTransaction.TransactionDate.ToString("d"));
                        ModelState.AddModelError("Balance", "Your balance will be $" + (stp.CashValuePortion - total));
                        ViewBag.DropDown = GetStockDropDown();
                        return View(stockTransaction);
                    }

                    else if (modify == true)
                    {
                        // Update cash value portion
                        stp.CashValuePortion -= total;
                        stp.TotalFees += 10;

                        // create stock transaction for purchase
                        stockTransaction.TotalPrice = -1 * (total - 10);
                        stockTransaction.StockPortfolio = stp;
                        stockTransaction.Stock = st;
                        stockTransaction.PricePerShare = st.CurrentPrice;
                        stockTransaction.StockTransactionType = StockTransactionTypes.Withdrawal;
                        stockTransaction.StockTransactionNumber = GenerateNextNum.GetNextTransactionNum(_context);
                        stockTransaction.StockTransactionNotes = "Stock Purchase - Account " + stp.PortfolioNumber.ToString();

                        // create a purchase fee stocktrans
                        StockTransaction fee = new()
                        {
                            TotalPrice = -10,
                            StockPortfolio = stp,
                            Stock = st,
                            StockTransactionType = StockTransactionTypes.Fee,
                            StockTransactionNumber = GenerateNextNum.GetNextTransactionNum(_context) + 1,
                            StockTransactionNotes = "Fee for purchase of " + st.StockName,
                            TransactionDate = stockTransaction.TransactionDate
                        };



                        _context.StockPortfolios.Update(stp);
                        _context.StockTransactions.Add(stockTransaction);
                        _context.StockTransactions.Add(fee);
                        await _context.SaveChangesAsync();

                        ViewBag.Balance = stp.CashValuePortion;
                        return View("PurchaseSuccess", stockTransaction);

                    }
                    else
                    {
                        return NotFound();
                    }


                }

                else
                {
                    return NotFound();
                }


            }
            else
            {
                ModelState.AddModelError("", "Please select a stock");
                ViewBag.DropDown = GetStockDropDown();
                return View(stockTransaction);

            }
        }

        public IActionResult PurchaseSuccess()
        {
            return View();
        }



        private IEnumerable<SelectListItem> GetStockDropDown()
        {
            // return stock properties in selectlist
            List<Stock> AllStocks = _context.Stocks.Include(s => s.StockType).ToList();


            List<SelectListItem> StockList = new();

            foreach (Stock st in AllStocks)
            {

                StockList.Add(new SelectListItem
                {
                    Text = st.StockName + "    " + st.TickerSymbol + "    " + st.
                    StockType.StockTypeName + "     $" + st.CurrentPrice + " + $10 purchase fee"
                    ,
                    Value = st.StockID.ToString()
                });

            }

            return StockList;

        }

        // Not used anymore
        //private SelectList GetAllStocks()
        //{
        //    List<Stock> StocksList = _context.Stocks.Include(s => s.StockType).ToList();
        //    SelectList AllStocksList = new SelectList(StocksList, "StockID", "StockDropDown");

        //    return AllStocksList;

        //}

        // GET: StockTransactions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.StockTransactions == null)
            {
                return NotFound();
            }

            var stockTransaction = await _context.StockTransactions.FindAsync(id);
            if (stockTransaction == null)
            {
                return NotFound();
            }
            return View(stockTransaction);
        }

        // POST: StockTransactions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.

LonghornBankWebApp/Views/StockTransactions/Create.cshtml
@model LonghornBankWebApp.Models.StockTransaction

@{
    ViewData["Title"] = "Buy Stock";
}

<h1>New Stock Transaction</h1>

<hr />
@section containerbottom{

    <div class="container min-vh-100 mt-4">
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        @Html.DropDownList("SelectedStock", @ViewBag.DropDown, "Select a Stock", new { @class = "form-control" })
                    </div>
                    <p><small><small>*Purchase fee is one time payment for transaction</small></small></p>
                    <div class="form-group">
                        <label asp-for="NumberOfShares" class="control-label"></label>
                        <input asp-for="NumberOfShares" class="form-control" />
                        <span asp-validation-for="NumberOfShares" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="TransactionDate" class="control-label"></label>
                        <input asp-for="TransactionDate" class="form-control" />
                        <span asp-validation-for="TransactionDate" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        @if (ViewData.ModelState.Keys.Contains("Succesful"))
                        {

                            <input type="submit" value="Confirm" asp-route-modify="@true" class="btn btn-success" />
                            <a asp-action="Create" class="btn btn-danger">Cancel</a>
                        }
                        else
                        {
                            <input type="submit" value="Create" asp-route-modify="@false" class="btn btn-primary" />
                        }

                    </div>
                </form>
                <a asp-action="Index" asp-controller="StockPortfolio">Back</a>

            </div>
            <div class="col-md-4">

                @if (ViewData.ModelState.Keys.Contains("Succesful"))
                {
                    <div class="alert alert-success" role="alert">
                        <p> @ViewData.ModelState["Succesful"].Errors[0].ErrorMessage</p>
                        <p> @ViewData.ModelState["Balance"].Errors[0].ErrorMessage</p>
                    </div>

                }


                @{

                    if (ViewData.ModelState.Keys.Contains("Not Enough Money!"))
                    {
                        <p class="text-danger">You do not have enough money in your portfolio to buy this many shares.</p>
                    }

                }
            </div>

        </div>
    </div>
}

LonghornBankWebApp/Views/StockTransactions/Delete.cshtml
@model LonghornBankWebApp.Models.StockTransaction

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StockTransaction</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StockTransactionNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StockTransactionNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PricePerShare)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PricePerShare)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfShares)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfShares)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TransactionDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TransactionDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StockTransactionType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StockTransactionType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StockTransactionNotes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StockTransactionNotes)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="StockTransactionID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LonghornBankWebApp/Views/StockTransactions/Details.cshtml
@model LonghornBankWebApp.Models.StockTransaction

@{
    ViewData["Title"] = "Stock Transaction Details";
}

<h1>Details</h1>

@section containerbottom{

    <div class="container min-vh-100 mt-4">
        <div>
            <h4>StockTransaction</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    Price per Share at Time of Purchase
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.PricePerShare)
                </dd>
                <dt class="col-sm-2">
                    Current Price per Share
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Stock.CurrentPrice)
                </dd>
                <dt class="col-sm-2">
                    Difference per Share
                </dt>
                <dd class="col-sm-10">
                    @{
                        var difference = Model.Stock.CurrentPrice - Model.PricePerShare;

                        // if the difference is negative
                        if (difference < 0)
                        {
                            <span style="color:red">@difference</span>
                        }

                        else if (difference > 0)
                        {
                            <span style="color:green">@difference</span>
                        }
                        else
                        {
                            <span style="color:blue">No Change</span>

                        }
                    }
                </dd>

                <dt class="col-sm-2">
                    @if (difference < 0)
                    {
                        <span style="color:red">Total Loss</span>
                    }
                    else if (difference > 0)
                    {
                        <span style="color:green">Total Gain</span>
                    }
                    else
                    {
                        <span style="color:blue">Total Gain/Loss</span>
                    }
                </dt>
                <dd class="col-sm-10">
                    @{
                        var totaldif = difference * ViewBag.Left;

                        @if (difference < 0)
                        {
                            <span style="color:red">@totaldif</span>
                        }
                        else if (difference > 0)
                        {
                            <span style="color:green">@totaldif</span>
                        }
                        else
                        {
                            <span style="color:blue">No Change</span>
                        }

                    }
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.NumberOfShares) Remaining
                </dt>
                <dd class="col-sm-10">
                    @ViewBag.Left
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.TransactionDate)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.TransactionDate)
                </dd>

            </dl>
        </div>
        <div>
            <!-- <a asp-action="Edit" asp-route-id="@Model?.StockTransactionID">Edit</a> |-->
            <a asp-action="SellStock" asp-route-id="@Model.StockPortfolio.StockPortfolioID">Back to List</a>
        </div>

    </div>
}

LonghornBankWebApp/Views/StockTransactions/Edit.cshtml
@model LonghornBankWebApp.Models.StockTransaction

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>StockTransaction</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="StockTransactionID" />
            <div class="form-group">
                <label asp-for="StockTransactionNumber" class="control-label"></label>
                <input asp-for="StockTransactionNumber" class="form-control" />
                <span asp-validation-for="StockTransactionNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PricePerShare" class="control-label"></label>
                <input asp-for="PricePerShare" class="form-control" />
                <span asp-validation-for="PricePerShare" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfShares" class="control-label"></label>
                <input asp-for="NumberOfShares" class="form-control" />
                <span asp-validation-for="NumberOfShares" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TransactionDate" class="control-label"></label>
                <input asp-for="TransactionDate" class="form-control" />
                <span asp-validation-for="TransactionDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StockTransactionType" class="control-label"></label>
                <select asp-for="StockTransactionType" class="form-control"></select>
                <span asp-validation-for="StockTransactionType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StockTransactionNotes" class="control-label"></label>
                <input asp-for="StockTransactionNotes" class="form-control" />
                <span asp-validation-for="StockTransactionNotes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

LonghornBankWebApp/Views/StockTransactions/Index.cshtml
@model IEnumerable<LonghornBankWebApp.Models.StockTransaction>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
@section containerbottom{

    <div class="container min-vh-100 mt-4">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.StockTransactionID)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PricePerShare)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.NumberOfShares)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TotalPrice)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TransactionDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.StockTransactionType)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.StockTransactionNotes)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.StockTransactionNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PricePerShare)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NumberOfShares)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TotalPrice)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TransactionDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StockTransactionType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StockTransactionNotes)
                        </td>
                        <td>
                            <a asp-action="StockTransDetails" asp-route-id="@item.StockTransactionID">Details</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
}

LonghornBankWebApp/Views/StockTransactions/PurchaseSuccess.cshtml
@model LonghornBankWebApp.Models.StockTransaction


@{
    ViewData["Title"] = "Purchase Summary";
}

<div class="alert alert-success" role="alert">
    Purchase has been completed successfully!
</div>

<h1>Sale Summary</h1>

@section containerbottom{

    <div class="container min-vh-100 mt-4">
        <div>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Stock.StockName)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Stock.StockName)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.NumberOfShares)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.NumberOfShares)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.TotalPrice)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.TotalPrice)
                </dd>
                <dt class="col-sm-2">
                    Associated Fees
                </dt>
                <dd class="col-sm-10">
                    $10 Transaction fee <br />
                    <small><small>*one time payment per transaction</small></small>
                </dd>
                <dt class="col-sm-2">
                    Cash Balance
                </dt>
                <dd class="col-sm-10">
                    @ViewBag.Balance

                </dd>
            </dl>
        </div>
        <div>
            <a class="btn btn-primary" asp-action="Index" asp-controller="StockPortfolio">Portfolio</a>
            <a class="btn btn-info" asp-action="Create">Purchase More</a>
        </div>
    </div>
}

LonghornBankWebApp/Views/StockTransactions/SellConfirm.cshtml
@model LonghornBankWebApp.Models.StockTransaction



@{

    ViewData["Title"] = "Order Summary";

}


<h1>Sale Summary</h1>
@section containerbottom{

    <div class="container min-vh-100 mt-4">
        <div>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Stock.StockName)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Stock.StockName)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.NumberOfShares) to Sell
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.NumberOfShares)
                </dd>
                <dt class="col-sm-2">
                    Shares Remaining
                </dt>
                <dd class="col-sm-10">
                    @ViewBag.Remaining from this initial purchase
                </dd>
                <dt class="col-sm-2">
                    Associated Fees
                </dt>
                <dd class="col-sm-10">
                    $15 Transaction fee <br />
                    <small><small>*one time payment per transaction</small></small>
                </dd>
                <dt class="col-sm-2">
                    Net Profit
                </dt>
                <dd class="col-sm-10">
                    @ViewBag.GainOrLoss
                </dd>
            </dl>
        </div>
        <div>
            <a class="btn btn-success" asp-action="Sell" asp-route-id="@Model.SellingTransactionNumber" asp-route-numShares="@Model.NumberOfShares" asp-route-profit="@ViewBag.GainOrLoss">Confirm</a>
            <a class="btn btn-danger" asp-action="SellStock" asp-route-id="@Model.StockPortfolio.StockPortfolioID">Cancel</a>
        </div>

    </div>
}

LonghornBankWebApp/Views/StockTransactions/SellStock.cshtml
@model IEnumerable<LonghornBankWebApp.Models.StockTransaction>


@{
    ViewData["Title"] = "Sell Holdings";
}

@section containerbottom{

    <div class="container min-vh-100 mt-4">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Stock Name
                    </th>
                    <th>
                        Purchase Price
                    </th>
                    <th>
                        Current Price
                    </th>
                    <th>
                        Transaction fee
                    </th>
                    <th>
                        Shares Held
                    </th>
                    <th>
                        Amount to Sell
                    </th>
                    <th>

                    </th>
                </tr>
            </thead>
            <tbody>

                <!-- Get the item and track index for use of viewbag dict-->
                @foreach (var item in Model)
                {

                    var stocksleft = ViewBag.StocksToSell[item.StockTransactionNumber];

                    var currentprice = item.Stock.CurrentPrice * item.NumberOfShares;



                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Stock.StockName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PricePerShare)
                        </td>
                        <td>
                            @*@currentprice.ToString("C")*@
                            $@item.Stock.CurrentPrice
                        </td>
                        <td>
                            <small><small>$15 transaction fee to sell</small></small>
                        </td>
                        <td>
                            @stocksleft.ToString()
                        </td>
                        @using (Html.BeginForm("SellConfirm", "StockTransactions", FormMethod.Post, new { @class = "form-inline" }))
                        {
                            <td>
                                @Html.TextBox("numShares", null, new { @class = "form-control", @Value = "1", @type = "number", @min = "1" ,@max = stocksleft})
                                <input type="hidden" name="id" value="@item.StockTransactionNumber" />
                                <input type="hidden" name="stockLeft" value="@stocksleft" />
                            </td>

                            <td>
                                <button type="submit" class="btn btn-primary">Sell</button>
                            </td>
                        }
                        <td>
                        </td>

                        <td>
                            <a class="btn btn-primary" asp-action="Details"
                       asp-route-id="@item.StockTransactionNumber" asp-route-stockLeft="@stocksleft">Details</a>
                        </td>
                    </tr>


                }
            </tbody>
        </table>
        <a asp-action="Index" asp-controller="StockPortfolio" class="btn btn-primary">Back</a>
    </div>
}