LonghornBankWebApp/Models/BankAccount.cs
using System.ComponentModel.DataAnnotations;



namespace LonghornBankWebApp.Models
{
    // User can have unlimited checking and savings but only one IRA account

    // This model class refers to the bank accounts made by users and not website account


    public enum BankAccountTypes { Checking, Savings, IRA }
    public class BankAccount
    {

        public Int32 BankAccountID { get; set; }

        [Display(Name = "Account Number")]
        public UInt32 BankAccountNumber { get; set; }


        // This has a default value if an active account and can be changed to customer preffered nickname
        [Display(Name = "Account Nickname")]
        public String BankAccountName { get; set; }

        // NOTE: Savings can only contain standard transaction (deposits/withdrawals/transfers)
        // Only account type and inital deposit required when making an account
        [Required]
        [Display(Name = "Account Type")]
        public BankAccountTypes BankAccountType { get; set; }



        [Display(Name = "Account Balance")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public Decimal BankAccountBalance { get; set; }


        public Boolean isActive { get; set; }

        public String TransferDropDown { get; set; }

        //// NOTE: which admin deactivated this account
        //public AppUser WhoDeactivated { get; set; }

        //CONSIDER: For IRA Might need to add a current contribution account to check if it max contribution has been met
        [Display(Name = "Total contribution")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public Decimal IRAContribution { get; set; }

        //CONSIDER: For IRA, might need method or property to see if qualified
        public Boolean IRAQualified { get; set; }


        //CONSIDER: This should just be a property in the view model when creating an account
        [Display(Name = "Initial Deposit")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public Decimal InitialDeposit { get; set; }



        // Navigational Properties


        public AppUser User { get; set; }


        public List<Transaction> Transactions { get; set; }



        //ADDED: prevent null value

        public BankAccount()
        {
            if (Transactions == null)
            {

                Transactions = new List<Transaction>();

            }
        }






    }
}

LonghornBankWebApp/Controllers/TransactionsController.cs
using LonghornBankWebApp.DAL;
using LonghornBankWebApp.Models;
using LonghornBankWebApp.Models.ViewModels;
using LonghornBankWebApp.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace LonghornBankWebApp.Controllers
{
    [Authorize]
    public class TransactionsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public TransactionsController(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Transactions
        public IActionResult Index(string SearchString, string selected, string order)
        {
            List<Transaction> all = new();
            if (User.IsInRole("Customer"))
            {
                all = _context.Transactions.Include(t => t.BankAccount).Include(t => t.StockPortfolio).Where(t => t.BankAccount.User.UserName == User.Identity.Name || t.StockPortfolio.User.UserName == User.Identity.Name).ToList();
            }

            // should employees see this too
            else if (User.IsInRole("Admin") || User.IsInRole("Employee"))
            {
                all = _context.Transactions.Include(t => t.BankAccount).Include(t => t.StockPortfolio).ToList();
            }



            ViewBag.total = all.Count;
            List<Transaction> queried = new();

            if (string.IsNullOrEmpty(SearchString) == false)
            {
                foreach (Transaction t in all)
                {
                    if (t.TransactionNotes != "" && t.TransactionNotes != null)
                    {
                        if (t.TransactionNotes.Contains(SearchString))
                        {
                            queried.Add(t);
                        }
                    }
                }
            }
            else
            {
                queried = all;
            }

            if (selected == "Number")
            {
                if (order == "Ascending")
                {
                    queried = queried.OrderBy(x => x.TransactionNumber).ToList();
                }
                else
                {
                    queried = queried.OrderByDescending(x => x.TransactionNumber).ToList();
                }
            }

            if (selected == "Type")
            {
                if (order == "Descending")
                {
                    queried = queried.OrderByDescending(x => x.TransactionType).ToList();
                }
                else
                {
                    queried = queried.OrderBy(x => x.TransactionType).ToList();
                }
            }
            if (selected == "Notes")
            {
                if (order == "Descending")
                {
                    queried = queried.OrderByDescending(x => x.TransactionNotes).ToList();
                }
                else
                {
                    queried = queried.OrderBy(x => x.TransactionNotes).ToList();
                }
            }
            if (selected == "Amount")
            {
                if (order == "Ascending")
                {
                    queried = queried.OrderBy(x => x.TransactionAmount).ToList();

                }
                else
                {
                    queried = queried.OrderByDescending(x => x.TransactionAmount).ToList();
                }
            }

            foreach (Transaction t in queried)
            {
                if (t.TransactionStatus == TransactionStatuses.Scheduled)
                {
                    if (t.TransactionDate <= DateTime.Today)
                    {
                        t.TransactionStatus = TransactionStatuses.Approved;
                        _context.Update(t);

                    }
                }
            }

            List<SelectListItem> sortby = new()
            {
                new SelectListItem(text: "Transaction Number", value: "Number"),
                new SelectListItem(text: "Transaction Type", value: "Type"),
                new SelectListItem(text: "Transaction Notes", value: "Notes"),
                new SelectListItem(text: "Transaction Amount", value: "Amount")
            };

            ViewBag.sortby = sortby;


            List<SelectListItem> orderList = new()
            {
                new SelectListItem(text: "Descending", value: "Descending"),
                new SelectListItem(text: "Ascending", value: "Ascending")
            };

            ViewBag.order = orderList;

            ViewBag.queriedCount = queried.Count;

            _context.SaveChanges();
            return View(queried);

        }

        // GET: Transactions/Details/5
        public async Task<IActionResult> Details(int? id, bool displayDispute = false)
        {
            if (id == null || _context.Transactions == null)
            {
                return NotFound();
            }

            var transaction = await _context.Transactions.Include(t => t.BankAccount).Include(t => t.StockPortfolio).Include(t => t.Disputes).FirstOrDefaultAsync(m => m.TransactionID == id);
            if (transaction == null)
            {
                return NotFound();
            }

            ViewBag.displayDispute = displayDispute;

            TransactionDispute td = new()
            {
                transaction = transaction
            };

            Dispute d = new();
            td.dispute = d;

            ViewBag.disputable = true;
            foreach (Dispute disp in transaction.Disputes)
            {
                if (disp.DisputeStatus == DisputeStatus.Submitted)
                {
                    ViewBag.action = true;
                    ViewBag.current = disp.DisputeID;
                    ViewBag.disputable = false;
                }

                if (disp.DisputeStatus == DisputeStatus.Accepted)
                {
                    ViewBag.disputable = false;
                }
            }

            return View(td);

            //return View(transaction);
        }


        [HttpGet]
        public IActionResult CreateDeposit()
        {
            AppUser u = _userManager.FindByNameAsync(User.Identity.Name).Result;
            if (u.IsActive == false)
            {
                return RedirectToAction("Index", "BankAccounts", new { message = "Your account is not active. Please contact an administrator to activate your account." });

            }
            Transaction deposit = new();
            ViewBag.SelectedBankAccount = 0;
            ViewBag.Accts = GetAllBankAccounts();
            return View(deposit);
        }

        public ActionResult DetailedSearch()
        {
            return View();
        }


        public ActionResult DisplaySearchResults(SearchViewModel svm)
        {
            var query = from r in _context.Transactions
                        select r;

            if (svm.TransactionDescription != null && svm.TransactionDescription != "") //user entered something
            {
                query = query.Where(r => r.TransactionNotes.Contains(svm.TransactionDescription));

            }

            if (svm.SelectedType != null)
            {
                query = query.Where(r => r.TransactionType == svm.SelectedType);
            }

            if (svm.TransactionNumber != null && svm.TransactionNumber != "") //user entered something
            {
                query = query.Where(r => r.TransactionNumber.ToString() == (svm.TransactionNumber));//not working currently - see what is wrong
            }

            if (svm.LowAmount != null && svm.HighAmount != null) //user entered something
            {
                query = query.Where(r => r.TransactionAmount < svm.HighAmount && r.TransactionAmount > svm.LowAmount);//ASK: does this include endpoints? 
            }

            if (svm.DateLow != null && svm.DateHigh != null)
            {
                query = query.Where(r => r.TransactionDate >= svm.DateLow && r.TransactionDate <= svm.DateHigh);//ASK: does this include endpoints
            }

            List<Transaction> SelectedTransactions = query.ToList();

            ViewBag.AllTransactions = _context.Transactions.Count();
            ViewBag.SelectedTransactions = SelectedTransactions.Count;

            return View("Index", SelectedTransactions);

        }








        [HttpPost]
        public IActionResult CreateDeposit(Transaction transaction, uint SelectedAccountNum, bool? modify)
        {
            bool isPortfolio = false;
            StockPortfolio dbStockPortfolio = new();

            if (transaction.TransactionDate < DateTime.Today)
            {
                ModelState.AddModelError(nameof(transaction.TransactionDate), "Transaction must be today or a future date");
            }

            AppUser u = _userManager.FindByNameAsync(User.Identity.Name).Result;

            if (u.IsActive == false)

            {
                return RedirectToAction("Index", "BankAccounts", new { message = "Your web account is not active. Please contact an administrator to activate your account." });

            }


            BankAccount dbBankAccount = _context.BankAccounts.Include(b => b.User).FirstOrDefault(b => b.BankAccountNumber == SelectedAccountNum && b.User.Email == User.Identity.Name);


            // for stock portfolios
            if (dbBankAccount == null)
            {
                isPortfolio = true;

                dbStockPortfolio = _context.StockPortfolios.Include(b => b.User).FirstOrDefault(b => b.PortfolioNumber == SelectedAccountNum && b.User.Email == User.Identity.Name);

                if (dbStockPortfolio.isActive == false)
                {

LonghornBankWebApp/Views/BankAccounts/Delete.cshtml
@model LonghornBankWebApp.Models.BankAccount

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BankAccount</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BankAccountNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BankAccountNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BankAccountName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BankAccountName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BankAccountType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BankAccountType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BankAccountBalance)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BankAccountBalance)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InitialDeposit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InitialDeposit)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BankAccountID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LonghornBankWebApp/Views/BankAccounts/Details.cshtml
@model LonghornBankWebApp.Models.BankAccount

@{
    ViewData["Title"] = "Details";
}

<h1>Bank Account Details</h1>

@section containerbottom{

    <div class="container min-vh-100 mt-4">
        <div>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.BankAccountNumber)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.BankAccountNumber)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.BankAccountName)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.BankAccountName)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.BankAccountType)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.BankAccountType)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.BankAccountBalance)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.BankAccountBalance)
                </dd>
                <dt class="col-sm-2">
                    Balance w/ scheduled transactions
                </dt>
                <dd class="col-sm-10">
                    $@ViewBag.withScheduled
                </dd>
                <dt class="col-sm-2">
                    Balance w/ pending transactions
                </dt>
                <dd class="col-sm-10">
                    $@ViewBag.withPending
                </dd>
                @if (Model.BankAccountType == BankAccountTypes.IRA)
                {
                    <dt class="col-sm-2">
                        Qualification Status
                    </dt>
                    @if (Model.IRAQualified == true)
                    {
                        <dd class="col-sm-10">
                            Qualified
                        </dd>
                    }
                    else
                    {
                        <dd class="col-sm-10">
                            Unqualified
                        </dd>
                    }
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.IRAContribution)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.IRAContribution)
                    </dd>
                }

            </dl>
        </div>
        <div>
            <a class="btn btn-info" asp-action="Edit" asp-route-id="@Model?.BankAccountID">Edit</a>
            <a class="btn btn-secondary" asp-action="Index">Back to List</a>
        </div>


        <br />

        @*<form asp-action="Index" asp-controller="Home" method="get">
    <p class="form-group">
    Search: <input name="SearchString" class="form-control" /><br />
    <button type="submit" class="btn btn-primary">Search</button>
    <a asp-action="DetailedSearch" class="btn btn-success">Detailed Search</a>
    <a asp-action="Index" class="btn btn-danger">Show All</a>
    </p>
    </form>*@




        <h4>Transactions for this Bank Account</h4>
        @*<a class="btn btn-success" asp-action="DetailedSearch" asp-route-id="@ViewBag.id">Detailed Search</a>
    <a asp-action="Details" asp-route-id="@Model.BankAccountID" class="btn btn-danger">Show All</a>*@


        <form asp-action="Details" asp-controller="BankAccounts" asp-route-id="@ViewBag.id" method="get">
            <main class="container-fluid">
                <div class="row">
                    <div class="col-3">
                        Search by description
                    </div>

                    <div class="col-3">
                        Select field to sort by
                    </div>
                    <div class="col-2">
                        Order by
                    </div>

                </div>
                <div class="row">
                    <div class="col-3">
                        <input name="SearchString" class="form-control" /><br />
                    </div>
                    <div class="col-3">
                        @Html.DropDownList("selected", (List<SelectListItem>)ViewBag.sortby, new { @class = "form-control" })
                    </div>

                    <div class="col-2">
                        @Html.DropDownList("order", (List<SelectListItem>)ViewBag.order, new { @class = "form-control" })
                    </div>

                    <div class="col">
                        <button type="submit" class="btn btn-primary">Apply</button>
                        <a class="btn btn-success" asp-action="DetailedSearch" asp-route-id="@ViewBag.id">Detailed Search</a>
                        <a asp-action="Details" asp-route-id="@Model.BankAccountID" class="btn btn-danger">Show All</a>
                    </div>

                </div>
            </main>
        </form>

        <p class="text-primary">Displaying @ViewBag.queried.Count records of @Model.Transactions.Count</p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Transaction #
                    </th>
                    <th>
                        Type
                    </th>
                    <th>
                        Notes
                    </th>
                    <th>
                        Amount
                    </th>
                    <th>
                        Date
                    </th>
                    <th>
                        Status
                    </th>
                </tr>
            </thead>

            @foreach (var transaction in ViewBag.queried)
            {
                <tr>
                    <td>
                        @transaction.TransactionNumber
                    </td>
                    <td>
                        @transaction.TransactionType
                    </td>
                    <td>
                        @*@Html.DisplayFor(modelItem => transaction.TransactionNotes)*@
                        @transaction.TransactionNotes
                    </td>
                    <td>
                        @*@Html.DisplayFor(modelItem => transaction.TransactionAmount)*@
                        $@transaction.TransactionAmount
                    </td>
                    <td>
                        @*@Html.DisplayFor(modelItem => transaction.TransactionDate)*@
                        @transaction.TransactionDate.ToString("MM-dd-yyyy")
                    </td>
                    @if (transaction.TransactionStatus == TransactionStatuses.Approved)
                    {
                        <td>
                            Completed
                        </td>
                    }
                    @if (transaction.TransactionStatus != TransactionStatuses.Approved)
                    {
                        <td>
                            @transaction.TransactionStatus
                        </td>
                    }
                    <td>
                        @*<a asp-controller="Transactions" asp-action="Edit" asp-route-id="@transaction.TransactionID">Edit</a> |*@
                        <a asp-controller="Transactions" asp-action="Details" asp-route-id="@transaction.TransactionID">Details</a>
                    </td>
                </tr>
            }
        </table>
    </div> 
}

LonghornBankWebApp/Views/BankAccounts/Index.cshtml
@model IEnumerable<LonghornBankWebApp.Models.BankAccount>

@{
    ViewData["Title"] = "Index";
}






@if (User.IsInRole("Customer"))
{
    @if (ViewBag.Message != null)
    {
        <div class="alert alert-warning" role="alert">
            @ViewBag.Message
        </div>
    }
    @if (ViewBag.Create != null)
    {
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Create a stock portfolio with us!</h4>
            <p>Get approved today</p>
            <hr>
            <a asp-action="Create" asp-controller="StockPortfolio" class="btn btn-outline-success">Create</a>
        </div>
    }
    
    <div>
        <h1 class="text-center">Your Bank Accounts</h1>
        <hr />
        <div align="center">
            <a class="btn btn-success"  asp-action="Create">Create New</a>
            <a class="btn btn-primary"  asp-controller="Transactions" asp-action="CreateDeposit">Deposit</a>
            <a class="btn btn-warning" asp-controller="Transactions" asp-action="CreateWithdrawal">Withdraw</a>
            <a class="btn btn-danger"asp-controller="Transactions" asp-action="CreateTransfer">Transfer</a>
        </div>

    </div>



        
   

}



@if (User.IsInRole("Admin") || User.IsInRole("Employee"))
{
    <h1>All Bank Accounts</h1>

    <form asp-action="Index" method="get">
        <p class="form-group">
            Search by Name: <input name="SearchString" class="form-control" /><br />
            <button type="submit" class="btn btn-primary">Search</button>
            <a asp-action="Index" class="btn btn-danger">Show All</a>
        </p>
    </form>

<p>Displaying @ViewBag.Selected of @ViewBag.All Customer Accounts.</p>

    
    
}

@if (User.IsInRole("Customer"))
{
    @section containerbottom{

    <div class="container min-vh-100 mt-4">
        <div class="row row-cols-1 row-cols-md-3 g-4">
            @foreach (var item in Model)
                {
                    <div class="col">
                        <div class="card">

                            @if (item.BankAccountNumber.ToString().Length < 10)
                            {
                                <div class="card-header">0</div>
                            }
                            else
                            {
                                <div class="card-header">
                                    @Html.DisplayFor(modelItem => item.BankAccountType) ending in @item.BankAccountNumber.ToString().Substring(item.BankAccountNumber.ToString().Length - 4)
                                </div>

                            }


                            <div class="card-body">
                                <h5 class="card-title">
                                    @Html.DisplayFor(modelItem => item.BankAccountName)
                                </h5>
                                <p class="card-text">
                                    Balance: @Html.DisplayFor(modelItem => item.BankAccountBalance)
                                </p>
                                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.BankAccountID">Edit</a>
                                <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.BankAccountID">Details</a>

                            </div>
                        </div>
                    </div>
                }
                @if (ViewBag.SP != null)
                {
                    <div class="col">
                        <div class="card">
                            @if (@ViewBag.SP.PortfolioNumber.ToString().Length < 10)
                            {
                                <div class="card-header">0</div>
                            }
                            else
                            {
                                <div class="card-header">
                                    Stock Portfolio ending in @ViewBag.SP.PortfolioNumber.ToString().Substring(ViewBag.SP.PortfolioNumber.ToString().Length - 4)
                                </div>
                            }
                            <div class="card-body">
                                <h5 class="card-title">
                                    @ViewBag.SP.PortfolioName
                                </h5>
                                <p class="card-text">
                                    @ViewBag.SP.CashValuePortion.ToString("C")
                                </p>
                                <a class="btn btn-primary" asp-controller="StockPortfolio" asp-action="Edit" asp-route-id="@ViewBag.SP.StockPortfolioID">Edit</a>
                                <a class="btn btn-primary" asp-controller="StockPortfolio" asp-action="Index">Details</a>

                            </div>
                        </div>
                    </div>
                }

            </div>



        </div>

    }
}

@if (User.IsInRole("Admin") || User.IsInRole("Employee"))
{

    @section containerbottom
    {
    <div class="container min-vh-100">
        <table class="table py-6">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.BankAccountNumber)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.BankAccountName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.BankAccountType)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.BankAccountBalance)
                    </th>

                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                    {
                        <tr>
                            @if (item.BankAccountNumber.ToString().Length < 10)
                            {
                                <td>
                                    0
                                </td>
                            }
                            else
                            {
                                <td>
                                    @*this way it only displays last four digits like proj req asks for*@
                                    @item.BankAccountNumber.ToString().Substring(item.BankAccountNumber.ToString().Length - 4)
                                </td>
                            }

                            <td>
                                @Html.DisplayFor(modelItem => item.BankAccountName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.BankAccountType)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.BankAccountBalance)
                            </td>

                            <td>
                                <a asp-action="Edit" asp-route-id="@item.BankAccountID">Edit</a> |
                                <a asp-action="Details" asp-route-id="@item.BankAccountID">Details</a>
                            </td>
                        </tr>
                    }

                    @if (ViewBag.SP != null)
                    {
                        <tr>
                            @if (@ViewBag.SP.PortfolioNumber.ToString().Length < 10)
                            {
                                <td>0</td>
                            }
                            else
                            {
                                <td>
                                    @ViewBag.SP.PortfolioNumber.ToString().Substring(ViewBag.SP.PortfolioNumber.ToString().Length - 4)
                                </td>
                            }

                            <td>
                                @ViewBag.SP.PortfolioName
                            </td>
                            <td>
                                Stock Portfolio
                            </td>
                            <td>
                                @ViewBag.SP.CashValuePortion.ToString("C")
                            </td>

                            <td>
                                <a asp-controller="StockPortfolio" asp-action="Edit" asp-route-id="@ViewBag.SP.StockPortfolioID">Edit</a> |
                                <a asp-controller="StockPortfolio" asp-action="Index">Details</a>
                            </td>
                        </tr>

                    }


                    @if (ViewBag.portfolios != null)
                    {
                        foreach (StockPortfolio sp in ViewBag.portfolios)
                        {
                            <tr>
                                @if (@sp.PortfolioNumber.ToString().Length < 10)
                                {
                                    <td>0</td>
                                }
                                else
                                {
                                    <td>
                                        @sp.PortfolioNumber.ToString().Substring(sp.PortfolioNumber.ToString().Length - 4)
                                    </td>
                                }

                                <td>
                                    @sp.PortfolioName
                                </td>
                                <td>
                                    Stock Portfolio
                                </td>
                                <td>
                                    @sp.CashValuePortion
                                </td>

                                <td>
                                    <a asp-controller="StockPortfolio" asp-action="Edit" asp-route-id="@sp.StockPortfolioID">Edit</a> |
                                    <a asp-controller="StockPortfolio" asp-action="Index" asp-route-id="@sp.StockPortfolioID">Details</a>
                                </td>
                            </tr>
                        }

                    }
                    <tr>
                    </tr>
                </tbody>
            </table>



        </div>
}
}